### PR TITLE
Practice Feature Area Refactor

### PR DESCRIPTION
**Pull request by noce2**
## Purpose

- As the number of features in the practice area have increased, it made sense to group them under the top resource as child components. This refactor also allows the possibility of "feature area chunking" (where the browser will only download a chunk of the app related to the relevant feature area.

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

- Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

- Test the code

```
npm test
npm run e2e
```

## What to Check

Verify that the following are valid

- npm test
```sh
Chrome Headless 85.0.4183.121 (Linux x86_64): Executed 67 of 70 (skipped 3) SUCCESS (1.737 secs / 1.512 secs)
TOTAL: 67 SUCCESS
TOTAL: 67 SUCCESS
```

- npm run e2e
```sh
Executed 12 of 12 specs SUCCESS in 9 secs.
[1] Randomized with seed 41851.
[1] [00:07:15] I/launcher - 0 instance(s) of WebDriver still running
[1] [00:07:15] I/launcher - chrome #01 passed
```

### CODE REVIEW

**Review by aakano684 — DISMISSED** [review]
May want to use a clarity design for the create question button but otherwise LGTM!

**Comment by noce2** [comment]
Thanks. Not sure where that went as I know you modified that button at some point and I should have brought it your changes.

**Comment by noce2** [comment]
> May want to use a clarity design for the create question button but otherwise LGTM!

Good shout. I rectified this in commit 0055c862f0b7ec860b07d1e34595613452cf49f0 which should get integrated via #74

**Review by noce2cicd — APPROVED** [review]
Approving as @aakano684 already did so previously.

**Pull request merged**
